language: ruby
rvm:
- 2.3.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: zuoxBh5kFHPinvJnGeWkheFf+q4ahy5oyKn6neGV897AoUvcMvrTt5Nx+p7jj+Q34nb0QQPOT15o/zWHw6Wm8oFRM2M43XSrzJYQbYGCuoI4PZXHpr0hGuLX/xysuDrft9YYGGyYvmddMjv+AQMUFwgZi+nWVkLC5zL/JDfamH3BJO2yXjKGVhWEn8VU97EPxmsFhnS0pw5kFfhN4rEnFJP+ymS4a8DgvawW1mt/UaAOKiYRL64X6UpakBUvqNveQDRzAnlco6qjxjaHoe6S2UcUekjBacGpSYzTrRge45+hatjNdkVMq9MdAphPY7PslN4jAaVPHdJuFSP1GaHwxebVzs4rNy+GoEE5QoTEOagYO6DFKlD79MmdwbWgFSb3lfW4sFoy2i+G+ZbGsdbLso0nD7nJhjgVNVa2XsQt9mA37DCLMTL1QOGq0ORCbWnEgY95v13skxShyrSe8/0CGxskpY9qqWg73kZxFFmodaLhgSTDQsOc1IJ3L93YCMjMgTaxEDI+vdgbZFIuRQz/wRVQPBffdBZrN5LZZJ9alMtKlutM8AC+CBIXbZpso/6pVGsLfYjmUKmzSjjBFaDKQQJmVhJlTGxinx+Qp0gChaPwz0+p81nGaHdlkawYfmnSf0baZ7FeTud0/MZbbZYZ3HwW/0SJF6i9PXP2PWR+FWo=
